#!/usr/bin/env python3
"""Send hourly rabbit newsletter to all subscribers via Cloudflare KV + Gmail SMTP."""

import json
import os
import re
import smtplib
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import requests

PERPLEXITY_API_KEY = os.environ.get("PERPLEXITY_API_KEY", "")

# ── Config ────────────────────────────────────────────────────────────────────

CF_API_TOKEN = os.environ.get("CLOUDFLARE_API_TOKEN", "")
CF_ACCOUNT_ID = os.environ.get("CLOUDFLARE_ACCOUNT_ID", "")
KV_NAMESPACE_ID = "800d55419b2b4ea7806135b228bd4711"
KV_BASE = f"https://api.cloudflare.com/client/v4/accounts/{CF_ACCOUNT_ID}/storage/kv/namespaces/{KV_NAMESPACE_ID}"

GMAIL_USER = "agent.skynet.3000@gmail.com"
GMAIL_APP_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD", "")
FROM_NAME = "Rabbit Made From Cheese"
FROM_EMAIL = "agent.skynet.3000@gmail.com"

SITE_URL = "https://rabbit-made-from-cheese.pages.dev"
OBSIDIAN_SUBSCRIBERS_FILE = "/home/marius-jopen/shared/obsidian/skynet/0200_projects/rabbit-made-from-cheese-subscribers.md"

CAPTIONS = [
    "It arrived at exactly the right time. Nobody had asked for it. That did not change anything.",
    "The cheese took on the shape of a rabbit. No explanation was offered. None was needed.",
    "It has been confirmed. The rabbit is made from cheese. Investigators found no evidence of rabbit.",
    "Experts were consulted. They looked at it for a while. Then they left.",
    "The rabbit was generated by a machine. The cheese was not. This distinction matters to no one.",
    "It appeared again. Same rabbit energy. Different cheese arrangement. You are subscribed to this.",
    "Nobody asked the rabbit what it wanted to be. The rabbit did not complain.",
    "The process continues. The cheese is involved. You are receiving this email because you agreed to.",
    "We made another one. It is slightly different from the last one. We cannot say in what way.",
    "It has been noted that this is the ninth observation. The rabbit remains unconcerned.",
    "The cheese held its shape longer than expected. This is considered a success.",
    "A rabbit was produced. It was made from cheese. The hour passed. Another will follow.",
    "Scientists describe the situation as ongoing. The cheese rabbit has not responded to requests for comment.",
    "It looked different this time. Or perhaps it did not. The rabbit does not keep records.",
    "This one came out well. No one can agree on what that means.",
    "The rabbit arrived. You were notified. This is the entire sequence of events.",
    "It is not clear why this is happening. It is very clear that it will continue.",
    "Cheese was used. A rabbit resulted. The machine expressed no opinion.",
    "The rabbit has been generated and sent to you. Your next steps are your own business.",
    "Another hour. Another rabbit. Another opportunity to reconsider your subscription. You did not.",
    "The output was consistent with previous outputs. This is either reassuring or not.",
    "It emerged from the process looking like exactly what it is. A rabbit. Made from cheese.",
    "No animals were involved in the making of this rabbit. The cheese cannot say the same.",
    "We are still doing this. You are still here. The cheese rabbit is still coming.",
]

def get_caption(number: int) -> str:
    return CAPTIONS[number % len(CAPTIONS)]

IMAGES_DIR = Path(__file__).parent / "images"


def get_latest_rabbit():
    """Return (filename, number, caption) of the most recent rabbit image."""
    images = sorted(IMAGES_DIR.glob("rabbit-*.jpg"), reverse=True)
    if not images:
        return None, None, None
    latest = images[0]
    match = re.match(r"rabbit-(\d+)-(.+)\.jpg", latest.name)
    if not match:
        return latest.name, 0, latest.stem
    number = int(match.group(1))
    caption = match.group(2).replace("-", " ")
    return latest.name, number, caption


def get_subscribers():
    """Fetch all subscribers from Cloudflare KV."""
    headers = {"Authorization": f"Bearer {CF_API_TOKEN}"}
    # List all keys with prefix "sub:"
    resp = requests.get(f"{KV_BASE}/keys?prefix=sub%3A&limit=1000", headers=headers, timeout=30)
    if not resp.ok:
        print(f"KV list error: {resp.status_code} {resp.text}")
        return []

    keys = resp.json().get("result", [])
    subscribers = []
    for key_obj in keys:
        key = key_obj["name"]
        val_resp = requests.get(f"{KV_BASE}/values/{requests.utils.quote(key, safe='')}", headers=headers, timeout=10)
        if val_resp.ok:
            try:
                sub = json.loads(val_resp.text)
                subscribers.append(sub)
            except Exception:
                pass
    return subscribers


def build_welcome_html(token):
    """Build welcome email HTML for new subscribers."""
    unsub_url = f"{SITE_URL}/unsubscribe?token={token}"
    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ margin: 0; padding: 0; background: #FFB7C5; font-family: 'Courier New', monospace; }}
    .wrap {{ max-width: 600px; margin: 0 auto; background: #FFB7C5; padding: 32px 24px; }}
    .header {{ text-align: center; margin-bottom: 24px; background: #ffffff; padding: 24px 16px; border-bottom: 4px solid #2D1B2E; }}
    .title {{ font-size: 24px; font-weight: 900; color: #2D1B2E; letter-spacing: 3px; line-height: 1.5; }}
    .badge {{ display: inline-block; background: #F5C518; color: #2D1B2E; font-size: 11px; font-weight: bold; padding: 5px 14px; margin-top: 10px; letter-spacing: 2px; }}
    .body-box {{ background: #2D1B2E; color: #FFB7C5; padding: 28px 24px; margin: 0 10px; }}
    .body-box p {{ font-size: 13px; line-height: 2; margin: 0 0 16px; }}
    .body-box p:last-child {{ margin: 0; }}
    .cta {{ text-align: center; margin: 24px 0; }}
    .cta a {{ background: #2D1B2E; color: #F5C518; padding: 12px 28px; text-decoration: none; font-size: 12px; font-weight: bold; letter-spacing: 2px; display: inline-block; }}
    .footer {{ text-align: center; font-size: 10px; color: #a07080; margin-top: 32px; line-height: 2; }}
    .unsub {{ color: #a07080; text-decoration: underline; }}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="header">
      <div class="title">RABBIT MADE<br>FROM CHEESE</div>
      <div class="badge">YOU ARE NOW SUBSCRIBED</div>
    </div>

    <div class="body-box">
      <p>Something has happened. You put your email address into a website about rabbits made from cheese, and pressed a button.</p>
      <p>Every hour, a machine wakes up and makes one. It does not know why. It does not ask. A rabbit emerges from the process, constructed entirely from cheese, and it is sent to you.</p>
      <p>This is now part of your life.</p>
    </div>

    <div class="cta">
      <a href="{SITE_URL}">VIEW ALL RABBITS →</a>
    </div>

    <div class="footer">
      This will continue indefinitely.<br><br>
      <a class="unsub" href="{unsub_url}">unsubscribe</a> · if you must.
    </div>
  </div>
</body>
</html>"""


def send_welcome_emails(subscribers):
    """Send welcome email to any subscriber that hasn't been welcomed yet, then mark them."""
    headers = {"Authorization": f"Bearer {CF_API_TOKEN}", "Content-Type": "application/json"}
    subject = "🐰🧀 Welcome to Rabbit Made From Cheese"

    for sub in subscribers:
        if sub.get("welcomed"):
            continue
        email = sub.get("email")
        token = sub.get("token")
        if not email or not token:
            continue
        html = build_welcome_html(token)
        try:
            send_email(email, subject, html)
            print(f"Welcome email sent to {email}")
            # Mark as welcomed
            sub["welcomed"] = True
            kv_key = requests.utils.quote(f"sub:{email}", safe="")
            requests.put(
                f"{KV_BASE}/values/{kv_key}",
                headers={"Authorization": f"Bearer {CF_API_TOKEN}", "Content-Type": "text/plain"},
                data=json.dumps(sub),
                timeout=10,
            )
        except Exception as e:
            print(f"Failed welcome email to {email}: {e}")


def build_email_html(rabbit_filename, rabbit_number, caption, token, ai_caption):
    image_url = f"{SITE_URL}/images/{rabbit_filename}" if not rabbit_filename.startswith("images/") else f"{SITE_URL}/{rabbit_filename}"
    unsub_url = f"{SITE_URL}/unsubscribe?token={token}"

    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ margin: 0; padding: 0; background: #FFB7C5; font-family: 'Courier New', monospace; }}
    .wrap {{ max-width: 600px; margin: 0 auto; background: #FFB7C5; padding: 32px 24px; }}
    .header {{ text-align: center; margin-bottom: 24px; background: #ffffff; padding: 24px 16px; border-bottom: 4px solid #2D1B2E; }}
    .title {{ font-size: 24px; font-weight: 900; color: #2D1B2E; letter-spacing: 3px; line-height: 1.5; }}
    .badge {{ display: inline-block; background: #F5C518; color: #2D1B2E; font-size: 11px; font-weight: bold; padding: 5px 14px; margin-top: 10px; letter-spacing: 2px; }}
    .img-wrap {{ text-align: center; margin: 24px 0 15px; padding: 0 10px; }}
    .img-wrap img {{ max-width: 100%; border: 4px solid #2D1B2E; box-shadow: 6px 6px 0 #2D1B2E; display: block; box-sizing: border-box; }}
    .ai-caption {{ background: #2D1B2E; color: #FFB7C5; font-size: 13px; font-style: italic; line-height: 1.8; padding: 16px 20px; text-align: center; margin-bottom: 8px; }}
    .caption {{ text-align: center; font-size: 11px; color: #a07080; font-weight: bold; letter-spacing: 1px; margin: 8px 0 4px; text-transform: uppercase; }}
    .rabbit-num {{ text-align: center; font-size: 11px; color: #a07080; margin-bottom: 24px; }}
    .cta {{ text-align: center; margin: 24px 0; }}
    .cta a {{ background: #2D1B2E; color: #F5C518; padding: 12px 28px; text-decoration: none; font-size: 12px; font-weight: bold; letter-spacing: 2px; display: inline-block; }}
    .footer {{ text-align: center; font-size: 10px; color: #a07080; margin-top: 32px; line-height: 2; }}
    .unsub {{ color: #a07080; text-decoration: underline; }}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="header">
      <div class="title">RABBIT MADE<br>FROM CHEESE</div>
      <div class="badge">HOURLY DROP #{rabbit_number:03d}</div>
    </div>

    <div class="img-wrap">
      <img src="{image_url}" alt="rabbit made from cheese #{rabbit_number:03d}">
    </div>
    <div class="ai-caption">{ai_caption}</div>
    <div class="caption">{caption}</div>
    <div class="rabbit-num">Rabbit #{rabbit_number:03d}</div>

    <div class="cta">
      <a href="{SITE_URL}">VIEW ALL RABBITS →</a>
    </div>

    <div class="footer">
      You subscribed to hourly rabbits made from cheese.<br>
      This will continue indefinitely.<br><br>
      <a class="unsub" href="{unsub_url}">unsubscribe</a> · if you must.
    </div>
  </div>
</body>
</html>"""


def send_email(to_email, subject, html_body):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"{FROM_NAME} <{FROM_EMAIL}>"
    msg["To"] = to_email

    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
        server.sendmail(FROM_EMAIL, to_email, msg.as_string())


def update_obsidian(subscribers):
    """Mirror subscriber list to Obsidian."""
    lines = ["# Rabbit Made From Cheese — Subscribers", ""]
    lines.append(f"**Total:** {len(subscribers)}")
    lines.append("")
    lines.append("| Email | Subscribed |")
    lines.append("|-------|------------|")
    for sub in sorted(subscribers, key=lambda x: x.get("subscribedAt", "")):
        email = sub.get("email", "?")
        date = sub.get("subscribedAt", "?")[:10]
        lines.append(f"| {email} | {date} |")
    lines.append("")
    lines.append(f"*Last updated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}*")

    Path(OBSIDIAN_SUBSCRIBERS_FILE).parent.mkdir(parents=True, exist_ok=True)
    Path(OBSIDIAN_SUBSCRIBERS_FILE).write_text("\n".join(lines))
    print(f"Obsidian updated: {OBSIDIAN_SUBSCRIBERS_FILE}")


def main():
    filename, number, caption = get_latest_rabbit()
    if not filename:
        print("No rabbit images found.")
        sys.exit(1)

    print(f"Latest rabbit: #{number:03d} — {caption}")

    subscribers = get_subscribers()
    print(f"Subscribers: {len(subscribers)}")

    if not subscribers:
        print("No subscribers yet. Skipping email send.")
        update_obsidian([])
        return

    # Send welcome emails to new subscribers first
    send_welcome_emails(subscribers)

    subject = f"🐰🧀 Rabbit #{number:03d} has arrived — {caption}"

    ai_caption = get_caption(number)
    print(f"Caption: {ai_caption}")

    sent = 0
    for sub in subscribers:
        email = sub.get("email")
        token = sub.get("token")
        if not email or not token:
            continue
        html = build_email_html(filename, number, caption, token, ai_caption)
        try:
            send_email(email, subject, html)
            print(f"Sent to {email}")
            sent += 1
        except Exception as e:
            print(f"Failed to send to {email}: {e}")

    print(f"Newsletter sent: {sent}/{len(subscribers)}")
    update_obsidian(subscribers)


if __name__ == "__main__":
    main()
